# Generated by Django 4.2.20 on 2025-03-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Раздел в менюто',
                'verbose_name_plural': 'Раздели в менюто',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, upload_to='menu', verbose_name='Снимка')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Раздел/група')),
            ],
            options={
                'verbose_name': 'Позиция в менюто',
                'verbose_name_plural': 'Позиции в менюто',
            },
        ),
    ]
